# Generated by Django 4.0.4 on 2022-05-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='verified_artist',
            new_name='verified_breed',
        ),
    ]
