# Generated by Django 4.0.4 on 2022-06-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_breeder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breeder',
            name='breeds',
        ),
    ]
